#! /usr/bin/env bash

{
    set -euo pipefail

    # more static analyzeds can be found here
    # https://pypi.org/project/pylint/

    mypy yasl.py --strict

    pylint yasl.py --disable=line-too-long,trailing-whitespace,fixme,missing-module-docstring,missing-function-docstring,use-implicit-booleaness-not-len,missing-class-docstring,broad-exception-raised,unspecified-encoding,too-many-return-statements,too-many-public-methods,consider-using-with,too-many-locals,too-many-statements,superfluous-parens,too-few-public-methods,wildcard-import,unused-wildcard-import,invalid-name
    # pylint definetely catches some mistakes that mypy doesn't
    # fixme - any todo comments

    # ruff check yasl.py
    # no idea if this actually helps if you already have `mypy` and `pylint`

    echo '~~~~~~~~~~~~~~~~~~~~~~'

    python3 yasl.py
}
